---
spring:
    application:
        name: '@project.name@'
    mvc:
        throw-exception-if-no-handler-found: true
    resources:
        add-mappings: false
    jackson:
        default-property-inclusion: NON_NULL

server:
    port: 8080

logging:
    level:
        root: ERROR
        de.hsrm.vegetables.service.Application: INFO
