---
spring:
    application:
        name: '@project.name@'
    mvc:
        throw-exception-if-no-handler-found: true

server:
    port: 8080

logging:
    level:
        root: ERROR
        de.hsrm.vegetables.service.Application: INFO
