openapi: "3.0.0"
info:
    description: |-
        This is the specification for the Stadtgemüse Service.
    version: "0.0.1-SNAPSHOT"
    title: "Stadtgemüse Service"

servers:
    -   url: "https://veg-service.herokuapp.com/"
        description: "Production"

tags:
    -   name: "Balance"
        description: "Handles balance requests"

paths:
    /balance/{name}:
        get:
            tags:
                - "Balance"
            summary: "Gets the current balance of the user"
            description: "Gets the current balance of the user, 0 if the user is not known"
            operationId: "balanceGet"
            parameters:
                - in: path
                  name: name
                  schema:
                      type: string
                  required: true
                  description: The name of the user
            responses:
                '200':
                    description: The current balance
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/balance-get-response'
        post:
            tags:
                - "Balance"
            summary: "Sets the balance"
            operationId: "balancePost"
            parameters:
                - in: path
                  name: name
                  schema:
                      type: string
                  required: true
                  description: The name of the user
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/balance-post-request'
            responses:
                '201':
                    description: Created

components:
    schemas:
        balance-get-response:
            description: A nice message form our service
            properties:
                balance:
                    type: number
        balance-post-request:
            description: A nice message form our service
            properties:
                balance:
                    type: number
