openapi: 3.0.3
info:
  description: This is the specification for the Stadtgemüse Service.
  version: 0.0.1-SNAPSHOT
  title: Stadtgemüse Service
  contact: { }
servers:
  -   url: 'https://veg-service.herokuapp.com/v1/'
      description: Production v1
tags:
  -   name: Balance
      description: Handles balance requests
  -   name: Stock
      description: All functionality related to the stock
  -   name: Purchase
      description: Functionality related to purchasing items
paths:
  '/balance/{name}':
    get:
      tags:
        - Balance
      summary: Gets the current balance of the user
      description: 'Gets the current balance of the user, or 0 if the user is currently not known'
      operationId: balanceGet
      parameters:
        -   $ref: '#/components/parameters/username'
      responses:
        '200':
          description: The current value of the balance for the specified user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/balance-response'
        default:
          description: Details about the error that occured
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
    patch:
      tags:
        - Balance
      summary: Changes the balance for the specified user
      operationId: balancePatch
      parameters:
        -   $ref: '#/components/parameters/username'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/balance-patch-request'
      responses:
        '200':
          description: The current value of the balance for the specified user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/balance-response'
        default:
          description: Details about the error that occured
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
  '/balance/{name}/topup':
    post:
      tags:
        - Balance
      summary: Topup the balance for the specified user
      operationId: balanceTopup
      parameters:
        -   $ref: '#/components/parameters/username'
      requestBody:
        description: 'Top up the balance with the amount, containing a positive value'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/balance-amount-request'
      responses:
        '200':
          description: The current value of the balance for the specified user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/balance-response'
        default:
          description: Details about the error that occured
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
  '/balance/{name}/withdraw':
    post:
      tags:
        - Balance
      summary: Withdraw the balance for the specified user
      operationId: balanceWithdraw
      parameters:
        -   $ref: '#/components/parameters/username'
      requestBody:
        description: 'Withdraw the amount from the balance, containing a positive value'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/balance-amount-request'
      responses:
        '200':
          description: The current value of the balance for the specified user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/balance-response'
        default:
          description: Details about the error that occured
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'

  '/stock':
    get:
      tags:
        - Stock
      summary: Retrieves all items currently in stock
      operationId: stockGet
      responses:
        '200':
          description: Successful call, returns the current stock
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/all-stock-response'
        default:
          description: Details about the error that occured
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
    post:
      tags:
        - Stock
      summary: Adds a new Item to the current stock
      operationId: stockPost
      requestBody:
        description: All data neccesary to create a new stock item
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/stock-post-request'
      responses:
        '201':
          description: Successful call, returns the created stock item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stock-response'
        default:
          description: Details about the error that occured
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
  '/stock/{item-id}':
    get:
      tags:
        - Stock
      summary: Retrieves information about a specific item in the stock
      operationId: stockItemGet
      parameters:
        -   $ref: '#/components/parameters/item-id'
      responses:
        '200':
          description: Successful call, returns the requested stock item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stock-response-by-id'
        default:
          description: Details about the error that occured
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
    patch:
      tags:
        - Stock
      summary: Updates data of an item
      operationId: stockPatch
      parameters:
        -   $ref: '#/components/parameters/item-id'
      requestBody:
        description: All data of an item that can be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/stock-patch-request'
      responses:
        '200':
          description: Successful call, returns the updated stock item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stock-response'
        default:
          description: Details about the error that occured
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
    delete:
      tags:
        - Stock
      summary: Soft deletes an item from the stock. It will no longer show up in the stock list, but information can still be retrieved
      operationId: stockDelete
      parameters:
        -   $ref: '#/components/parameters/item-id'
      responses:
        '204':
          description: The stock item was successfully soft-deleted
        default:
          description: Details about the error that occured
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'

  '/purchase/{name}':
    post:
      tags:
        - Purchase
      summary: Adds a new Item to the current stock
      parameters:
        -   $ref: '#/components/parameters/username'
      operationId: purchaseFromStock
      requestBody:
        description: All items that the user wants to purchase
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/purchase-request'
      responses:
        '200':
          description: Successful call, returns the price of what was purchase and the new balance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/purchase-response'
        default:
          description: Details about the error that occured
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'

components:
  schemas:

    #
    # Error Schemas
    #

    error-response:
      description: "Contains details about the occurred error"
      type: object
      required:
        - errorCode
        - status
        - errorMessage
      properties:
        errorCode:
          description: "Number, that can be referenced to a specific error"
          example: 400001
          type: integer
        status:
          description: "HTTP Status Code returned"
          example: 400
          type: integer
        message:
          description: "A detailed error message"
          example: "Validation failed"
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/error-detail'
    error-detail:
      description: A more precise explaination of an error
      type: object
      properties:
        message:
          description: A message relating to the error detail
          type: string
          example: "Invalid request parameter: balance"
        detail:
          description: A detailed message of the error
          type: string
          example: "The value null does not match the Specification"

    #
    # Request Schemas
    #

    balance-patch-request:
      type: object
      description: Contains data about how to change the balance
      required:
        - balance
      properties:
        balance:
          description: Absolute balance to be applied instead of the current balance
          example: 60
          type: number
          format: float

    balance-amount-request:
      description: Contains data about the amount you want to change the balance
      type: object
      required:
        - amount
      properties:
        amount:
          description: Realative amount to be applied to the balance
          example: 60
          minimum: 0
          type: number
          format: float

    purchase-request:
      description: All items that the user wants to purchase
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/cart-item'

    stock-post-request:
      description: All possible fields to set when creating a new item in stock
      type: object
      required:
        - name
        - unitType
        - quantity
        - pricePerItem
      properties:
        name:
          $ref: '#/components/schemas/item-name'
        unitType:
          $ref: '#/components/schemas/unitType'
        quantity:
          $ref: '#/components/schemas/quantity'
        pricePerItem:
          $ref: '#/components/schemas/pricePerItem'

    stock-patch-request:
      description: All data of an item that can be updated
      type: object
      properties:
        name:
          $ref: '#/components/schemas/item-name'
        unitType:
          $ref: '#/components/schemas/unitType'
        quantity:
          $ref: '#/components/schemas/quantity'
        pricePerItem:
          $ref: '#/components/schemas/pricePerItem'


    #
    # Response Schemas
    #

        balance-response:
            description: Contains data about the current balance
            type: object
            required:
                - balance
                - name
            properties:
                balance:
                    description: The current balance
                    example: 10
                    type: number
                    format: float
                name:
                    description: The name of the owner of this balance
                    example: Robby
                    type: string

    parameters:
        username:
            in: path
            name: name
            schema:
                type: string
                maxLength: 255
            required: true
            description: The unique name of the user
