openapi: "3.0.0"
info:
    description: |-
        This is the specification for the Stadtgemüse Service.
    version: "0.0.1-SNAPSHOT"
    title: "Stadtgemüse Service"

servers:
    -   url: "https://veg-service.herokuapp.com/"
        description: "Production"

tags:
    -   name: "Balance"
        description: "Handles balance requests"

paths:
    /balance/{name}:
        get:
            tags:
                - "Balance"
            summary: "Gets the current balance of the user"
            description: "Gets the current balance of the user, or 0 if the user is currently not known"
            operationId: "balanceGet"
            parameters:
                - in: path
                  name: name
                  schema:
                      type: string
                  required: true
                  description: "The unique name of the user"
            responses:
                '200':
                    description: "The current value of the balance for the specified user"
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/balance-get-response'
        post:
            tags:
                - "Balance"
            summary: "Sets the balance for the specified user"
            operationId: "balancePost"
            parameters:
                - in: path
                  name: name
                  schema:
                      type: string
                  required: true
                  description: "The unique name of the user"
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/balance-post-request'
            responses:
                '200':
                    description: "Updated the balance for the user successfully"
                '400':
                    description: "Both values were set, only one at a time allowed"

components:
    schemas:
        balance-get-response:
            description: "Contains data about the current balance"
            properties:
                balance:
                    description: "The current balance"
                    example: 10
                    type: number
                    format: float
        balance-post-request:
            description: "Contains data about how to update the balance"
            properties:
                balanceDifference:
                    description: "Relative number to be added to the current balance"
                    example: -2.4
                    type: number
                    format: float
                balance:
                    description: "Absolute balance to be applied instead of the current balance"
                    example: 60
                    type: number
                    format: float